pip install pyqt5
pip install pyrebase4
pip install xlrd==1.2.0
pip install selenium==4.2.0
pip install pyautogui
pip install pywin32
pip install docxpy
pip install pyperclip
pip install pillow
